###
GET http://www.localhost:3000/todos/?status=TO%20DO
### 
GET http://www.localhost:3000/todos/?priority=HIGH

###
GET http://www.localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

### 
GET http://www.localhost:3000/todos/?category=WORK&status=DONE

### 
GET http://www.localhost:3000/todos/?category=HOME

### 
GET http://www.localhost:3000/todos/?category=LEARNING&priority=HIGH

###  
GET http://www.localhost:3000/todos/?search_q=Buy

### 
GET http://www.localhost:3000/todos/3/

### 
GET http://www.localhost:3000/agenda/
### 
POST  http://www.localhost:3000/todos/
Content-Type: application/json

{
  "id": 9,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-2-22"
}
###

PUT http://www.localhost:3000/todos/9/
Content-Type: application/json


   {
  "status": "TO DO"
}